# Staging environment - as production except for domain
volumes:
  django-media:

services:
  frontend:
    image: ghcr.io/nismod/jsrat-frontend:canary
    platform: linux/amd64
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/nismod/jsrat-backend:0.2
    platform: linux/amd64
    build: ./backend
    ports:
      - "3001:80"
    env_file:
      - ./envs/.backend.env
    volumes:
      - django-media:/code/media

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver:0.1
    platform: linux/amd64
    build:
      context: ./tileserver/vector
    command:
      [
        "tileserver-gl-light",
        "-c",
        "config.json",
        "-p",
        "8080",
        "--verbose",
        "-u",
        "https://jamaica.infrastructureresilience.org/vector", #this matches the URL of the hosting server
      ]
    ports:
      - "3002:8080"
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json
