# Development environment - includes database, hard-coded env vars
volumes:
  postgis-data:
  django-media:

services:
  traefik:
    image: "traefik:v3.6"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entryPoints.web.address=:80"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/configuration:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/certs"

  frontend:
    image: ghcr.io/nismod/irvapp-frontend:0.1
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  django:
    image: ghcr.io/nismod/irvapp-backend:0.1
    build: ./irvapp
    environment:
      - PGHOST=db
      - PGDATABASE=jamaicadev
      - PGUSER=docker
      - PGPASSWORD=docker
      - PIXEL_STACK_DATA_DIR=/data/pixel
      - LAYER_METADATA_PATH=/data/pixel/hazard_layers.csv
      - TILEDB_URI=/data/raster
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./irvapp:/code
      - django-media:/code/media
      - ./tileserver/stacks:/data/pixel:ro
      - ./tileserver/raster/data:/data/raster:ro
      - ./etl/hazard_layers.csv:/data/pixel/hazard_layers.csv:ro
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/static/`) || PathPrefix(`/media/`) || PathPrefix(`/martor/`) || PathPrefix(`/accounts/`))"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.routers.django.middlewares=django-stripprefix"
      - "traefik.http.middlewares.django-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  vector-tileserver:
    image: ghcr.io/nismod/irvapp-vector-tileserver-dev:0.1
    build: ./tileserver/vector
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    shm_size: 1g
    environment:
      - POSTGRES_DB=jamaicadev
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - WAL_SIZE=4GB
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d jamaicadev"
      interval: 10s
      timeout: 5s
      retries: 5

  raster-tile-ingester:
    build: ./irvapp
    profiles: ["raster-tile-ingester"]
    volumes:
      - ./tileserver/raster/data:/data/raster:rw
    environment:
      - RASTER_BASE_PATH=/data/raster
    command: ["python", "manage.py", "ingest_rasters"]
