# Development environment - includes database, hard-coded env vars
volumes:
  postgis-data:

services:
  traefik:
    image: "traefik:v3.6"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entryPoints.web.address=:80"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/configuration:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/certs"

  frontend:
    image: ghcr.io/nismod/jsrat-frontend:0.1
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  django:
    build: ./irvapp
    environment:
      - PGHOST=db
      - PGDATABASE=jamaicadev
      - PGUSER=docker
      - PGPASSWORD=docker
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./irvapp:/code
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  backend:
    image: ghcr.io/nismod/jsrat-backend:0.2
    build: ./backend
    ports:
      - 8888:80
    environment:
      - PGHOST=db
      - PGDATABASE=jamaicadev
      - PGUSER=docker
      - PGPASSWORD=docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver-dev:0.1
    build: ./tileserver/vector
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json
    ports:
      - 8800:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vector-tileserver.rule=Host(`localhost`) && PathPrefix(`/vector`)"
      - "traefik.http.routers.vector-tileserver.entrypoints=web"
      - "traefik.http.routers.vector-tileserver.middlewares=vector-tileserver-stripprefix"
      - "traefik.http.middlewares.vector-tileserver-stripprefix.stripprefix.prefixes=/vector"
      - "traefik.http.services.vector-tileserver.loadbalancer.server.port=8080"

  raster-tileserver:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.2
    build: ./tileserver/raster
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    ports:
      - 5001:5000
    environment:
      - TC_DRIVER_PATH=/data/terracotta.sqlite
      - TC_RESAMPLING_METHOD=nearest
      - TC_REPROJECTION_METHOD=nearest
      - TC_PNG_COMPRESS_LEVEL=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raster-tileserver.rule=Host(`localhost`) && PathPrefix(`/raster`)"
      - "traefik.http.routers.raster-tileserver.entrypoints=web"
      - "traefik.http.routers.raster-tileserver.middlewares=raster-tileserver-stripprefix"
      - "traefik.http.middlewares.raster-tileserver-stripprefix.stripprefix.prefixes=/raster"
      - "traefik.http.services.raster-tileserver.loadbalancer.server.port=5000"

  pixel-driller:
    build: ./pixel_driller
    volumes:
      - ./tileserver/stacks:/data
      - ./pixel_driller:/code
      - ./etl/hazard_layers.csv:/data/hazard_layers.csv
    ports:
      - 5080:80
    environment:
      - PIXEL_STACK_DATA_DIR=/data
      - LAYER_METADATA_PATH=/data/hazard_layers.csv
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pixel-driller.rule=Host(`localhost`) && PathPrefix(`/pixel`)"
      - "traefik.http.routers.pixel-driller.entrypoints=web"
      - "traefik.http.routers.pixel-driller.middlewares=pixel-driller-stripprefix"
      - "traefik.http.middlewares.pixel-driller-stripprefix.stripprefix.prefixes=/pixel"
      - "traefik.http.services.pixel-driller.loadbalancer.server.port=80"

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    shm_size: 1g
    environment:
      - POSTGRES_DB=jamaicadev
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - WAL_SIZE=4GB
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d jamaicadev"

  raster-tile-ingester:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.2
    build: ./tileserver/raster
    profiles: ["raster-tile-ingester"]
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    command:
      [
        "terracotta",
        "ingest",
        "/data/{type}__rp_{rp}__rcp_{rcp}__epoch_{epoch}__conf_{confidence}.tif",
        "-o",
        "/data/terracotta.sqlite",
      ]
