# Staging environment - as production except for domain
volumes:
  django-media:

services:
  frontend:
    image: ghcr.io/nismod/jsrat-frontend:canary
    platform: linux/amd64
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/nismod/jsrat-backend:0.2
    platform: linux/amd64
    build: ./backend
    ports:
      - "3001:80"
    env_file:
      - ./envs/.backend.env
    volumes:
      - django-media:/code/media

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver:0.1
    platform: linux/amd64
    build:
      context: ./tileserver/vector
    command:
      [
        "tileserver-gl-light",
        "-c",
        "config.json",
        "-p",
        "8080",
        "--verbose",
        "-u",
        "https://jamaica.infrastructureresilience.org/vector", #this matches the URL of the hosting server
      ]
    ports:
      - "3002:8080"
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json

  raster-tile-ingester:
    image: ghcr.io/nismod/jsrat-backend:0.2
    build: ./irvapp
    profiles: ["raster-tile-ingester"]
    volumes:
      - ./tileserver/raster/data:/data/raster
    environment:
      - RASTER_BASE_PATH=/data/raster
    command: ["python", "manage.py", "ingest_rasters"]

  pixel-driller:
    image: ghcr.io/nismod/jsrat-pixel-driller:canary
    platform: linux/amd64
    build: ./pixel_driller
    ports:
      - "3004:80"
    volumes:
      - ./tileserver/stacks:/data
    environment:
      - PIXEL_STACK_DATA_DIR=/data
      - LAYER_METADATA_PATH=/data/hazard_layers.csv
