# Development environment - includes database, hard-coded env vars
volumes:
  postgis-data:

services:
  traefik:
    image: "traefik:v3.6"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entryPoints.web.address=:80"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./traefik/configuration:/configuration"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/certs"

  frontend:
    image: ghcr.io/nismod/jsrat-frontend:0.1
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  django:
    build: ./irvapp
    environment:
      - PGHOST=db
      - PGDATABASE=jamaicadev
      - PGUSER=docker
      - PGPASSWORD=docker
      - PIXEL_STACK_DATA_DIR=/data
      - LAYER_METADATA_PATH=/data/hazard_layers.csv
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./irvapp:/code
      - ./tileserver/stacks:/data
      - ./etl/hazard_layers.csv:/data/hazard_layers.csv
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.django.entrypoints=web"
      - "traefik.http.routers.django.middlewares=django-stripprefix"
      - "traefik.http.middlewares.django-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver-dev:0.1
    build: ./tileserver/vector
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json

  raster-tileserver:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.2
    build: ./tileserver/raster
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    environment:
      - TC_DRIVER_PATH=/data/terracotta.sqlite
      - TC_RESAMPLING_METHOD=nearest
      - TC_REPROJECTION_METHOD=nearest
      - TC_PNG_COMPRESS_LEVEL=1

  db:
    image: kartoza/postgis:14-3.1
    volumes:
      - postgis-data:/var/lib/postgresql
    shm_size: 1g
    environment:
      - POSTGRES_DB=jamaicadev
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
      - WAL_SIZE=4GB
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=docker pg_isready -h 127.0.0.1 -U docker -d jamaicadev"
      interval: 10s
      timeout: 5s
      retries: 5

  raster-tile-ingester:
    image: ghcr.io/nismod/jsrat-raster-tileserver:0.2
    build: ./tileserver/raster
    profiles: ["raster-tile-ingester"]
    volumes:
      - ./tileserver/raster/data:/data
      - ./tileserver/raster/config.toml:/config.toml
    command:
      [
        "terracotta",
        "ingest",
        "/data/{type}__rp_{rp}__rcp_{rcp}__epoch_{epoch}__conf_{confidence}.tif",
        "-o",
        "/data/terracotta.sqlite",
      ]
