# Production environment
volumes:
  django-media:

services:
  frontend:
    image: ghcr.io/nismod/irvapp-frontend:0.1
    build: ./frontend
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/nismod/irvapp-backend:0.2
    build: ./irvapp
    ports:
      - "3001:80"
    env_file:
      - ./envs/prod/.backend.env
    volumes:
      - django-media:/code/media

  vector-tileserver:
    image: ghcr.io/nismod/jsrat-vector-tileserver:0.1
    build:
      context: ./tileserver/vector
    command:
      [
        "tileserver-gl-light",
        "-c",
        "config.json",
        "-p",
        "8080",
        "--verbose",
        "-u",
        "https://jsrat.licj.org.jm:9443/vector", #this matches the URL of the hosting server
      ]
    ports:
      - "3002:8080"
    volumes:
      - ./tileserver/vector/data:/data
      - ./tileserver/vector/config.json:/config.json
