# Generated by Django 6.0.7 on 2026-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastertilesource',
            name='database',
            field=models.CharField(default='terracotta.sqlite', max_length=255),
        ),
    ]
