// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type AdaptationCostBenefit = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type AttributeLookupRequest = {
    ids: Array<number>;
};

export type DamagesExpected = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpv = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRp = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type Feature = {
    readonly id: number;
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetail = {
    readonly id: number;
    readonly adaptation: Array<AdaptationCostBenefit>;
    readonly damages_expected: Array<DamagesExpected>;
    readonly damages_return_period: Array<DamagesRp>;
    readonly damages_npv: Array<DamagesNpv>;
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type PaginatedAdaptationCostBenefitList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefit>;
};

export type PaginatedDamagesExpectedList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpected>;
};

export type PaginatedDamagesRpList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRp>;
};

export type PaginatedFeatureList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Feature>;
};

export type PaginatedSortedFeatureListResponse = {
    items: Array<SortedFeature>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type PatchedAdaptationCostBenefit = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    adaptation_name?: string;
    adaptation_protection_level?: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesExpected = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    epoch?: number;
    protection_standard?: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesRp = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    epoch?: number;
    rp?: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature?: number;
};

export type PatchedFeature = {
    readonly id?: number;
    string_id?: string;
    layer?: string;
    sublayer?: string | null;
    properties?: unknown;
};

export type ProtectedFeature = {
    id: number;
    string_id: string;
    layer: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    adaptation_cost: number | null;
    avoided_ead_mean: number | null;
    avoided_eael_mean: number | null;
    hazard: string;
    rcp: string;
};

export type SortedFeature = {
    id: number;
    string_id: string;
    layer: string;
    bbox_wkt: string;
    value: number | null;
};

export type AdaptationCostBenefitWritable = {
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type DamagesExpectedWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpvWritable = {
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRpWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type FeatureWritable = {
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetailWritable = {
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type PaginatedAdaptationCostBenefitListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefitWritable>;
};

export type PaginatedDamagesExpectedListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpectedWritable>;
};

export type PaginatedDamagesRpListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRpWritable>;
};

export type PaginatedFeatureListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<FeatureWritable>;
};

export type PatchedAdaptationCostBenefitWritable = {
    hazard?: string;
    rcp?: string;
    adaptation_name?: string;
    adaptation_protection_level?: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesExpectedWritable = {
    hazard?: string;
    rcp?: string;
    epoch?: number;
    protection_standard?: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesRpWritable = {
    hazard?: string;
    rcp?: string;
    epoch?: number;
    rp?: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature?: number;
};

export type PatchedFeatureWritable = {
    string_id?: string;
    layer?: string;
    sublayer?: string | null;
    properties?: unknown;
};

export type AdaptationCostBenefitsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/adaptation-cost-benefits';
};

export type AdaptationCostBenefitsListResponses = {
    200: PaginatedAdaptationCostBenefitList;
};

export type AdaptationCostBenefitsListResponse = AdaptationCostBenefitsListResponses[keyof AdaptationCostBenefitsListResponses];

export type AdaptationCostBenefitsCreateData = {
    body: AdaptationCostBenefitWritable;
    path?: never;
    query?: never;
    url: '/adaptation-cost-benefits';
};

export type AdaptationCostBenefitsCreateResponses = {
    201: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsCreateResponse = AdaptationCostBenefitsCreateResponses[keyof AdaptationCostBenefitsCreateResponses];

export type AdaptationCostBenefitsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AdaptationCostBenefitsDestroyResponse = AdaptationCostBenefitsDestroyResponses[keyof AdaptationCostBenefitsDestroyResponses];

export type AdaptationCostBenefitsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsRetrieveResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsRetrieveResponse = AdaptationCostBenefitsRetrieveResponses[keyof AdaptationCostBenefitsRetrieveResponses];

export type AdaptationCostBenefitsPartialUpdateData = {
    body?: PatchedAdaptationCostBenefitWritable;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsPartialUpdateResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsPartialUpdateResponse = AdaptationCostBenefitsPartialUpdateResponses[keyof AdaptationCostBenefitsPartialUpdateResponses];

export type AdaptationCostBenefitsUpdateData = {
    body: AdaptationCostBenefitWritable;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsUpdateResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsUpdateResponse = AdaptationCostBenefitsUpdateResponses[keyof AdaptationCostBenefitsUpdateResponses];

export type AttributesCreateData = {
    body: AttributeLookupRequest;
    path: {
        field_group: string;
    };
    query: {
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to look up
         */
        field: string;
        /**
         * Asset layer ID
         */
        layer: string;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
    };
    url: '/attributes/{field_group}';
};

export type AttributesCreateResponses = {
    200: {
        [key: string]: number | null;
    };
};

export type AttributesCreateResponse = AttributesCreateResponses[keyof AttributesCreateResponses];

export type DamagesExpectedListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/damages-expected';
};

export type DamagesExpectedListResponses = {
    200: PaginatedDamagesExpectedList;
};

export type DamagesExpectedListResponse = DamagesExpectedListResponses[keyof DamagesExpectedListResponses];

export type DamagesExpectedCreateData = {
    body: DamagesExpectedWritable;
    path?: never;
    query?: never;
    url: '/damages-expected';
};

export type DamagesExpectedCreateResponses = {
    201: DamagesExpected;
};

export type DamagesExpectedCreateResponse = DamagesExpectedCreateResponses[keyof DamagesExpectedCreateResponses];

export type DamagesExpectedDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DamagesExpectedDestroyResponse = DamagesExpectedDestroyResponses[keyof DamagesExpectedDestroyResponses];

export type DamagesExpectedRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedRetrieveResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedRetrieveResponse = DamagesExpectedRetrieveResponses[keyof DamagesExpectedRetrieveResponses];

export type DamagesExpectedPartialUpdateData = {
    body?: PatchedDamagesExpectedWritable;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedPartialUpdateResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedPartialUpdateResponse = DamagesExpectedPartialUpdateResponses[keyof DamagesExpectedPartialUpdateResponses];

export type DamagesExpectedUpdateData = {
    body: DamagesExpectedWritable;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedUpdateResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedUpdateResponse = DamagesExpectedUpdateResponses[keyof DamagesExpectedUpdateResponses];

export type DamagesRpListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/damages-rp';
};

export type DamagesRpListResponses = {
    200: PaginatedDamagesRpList;
};

export type DamagesRpListResponse = DamagesRpListResponses[keyof DamagesRpListResponses];

export type DamagesRpCreateData = {
    body: DamagesRpWritable;
    path?: never;
    query?: never;
    url: '/damages-rp';
};

export type DamagesRpCreateResponses = {
    201: DamagesRp;
};

export type DamagesRpCreateResponse = DamagesRpCreateResponses[keyof DamagesRpCreateResponses];

export type DamagesRpDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DamagesRpDestroyResponse = DamagesRpDestroyResponses[keyof DamagesRpDestroyResponses];

export type DamagesRpRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpRetrieveResponses = {
    200: DamagesRp;
};

export type DamagesRpRetrieveResponse = DamagesRpRetrieveResponses[keyof DamagesRpRetrieveResponses];

export type DamagesRpPartialUpdateData = {
    body?: PatchedDamagesRpWritable;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpPartialUpdateResponses = {
    200: DamagesRp;
};

export type DamagesRpPartialUpdateResponse = DamagesRpPartialUpdateResponses[keyof DamagesRpPartialUpdateResponses];

export type DamagesRpUpdateData = {
    body: DamagesRpWritable;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpUpdateResponses = {
    200: DamagesRp;
};

export type DamagesRpUpdateResponse = DamagesRpUpdateResponses[keyof DamagesRpUpdateResponses];

export type FeaturesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/features';
};

export type FeaturesListResponses = {
    200: PaginatedFeatureList;
};

export type FeaturesListResponse = FeaturesListResponses[keyof FeaturesListResponses];

export type FeaturesCreateData = {
    body: FeatureWritable;
    path?: never;
    query?: never;
    url: '/features';
};

export type FeaturesCreateResponses = {
    201: Feature;
};

export type FeaturesCreateResponse = FeaturesCreateResponses[keyof FeaturesCreateResponses];

export type FeaturesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type FeaturesDestroyResponse = FeaturesDestroyResponses[keyof FeaturesDestroyResponses];

export type FeaturesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesRetrieveResponses = {
    200: FeatureDetail;
};

export type FeaturesRetrieveResponse = FeaturesRetrieveResponses[keyof FeaturesRetrieveResponses];

export type FeaturesPartialUpdateData = {
    body?: PatchedFeatureWritable;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesPartialUpdateResponses = {
    200: Feature;
};

export type FeaturesPartialUpdateResponse = FeaturesPartialUpdateResponses[keyof FeaturesPartialUpdateResponses];

export type FeaturesUpdateData = {
    body: FeatureWritable;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesUpdateResponses = {
    200: Feature;
};

export type FeaturesUpdateResponse = FeaturesUpdateResponses[keyof FeaturesUpdateResponses];

export type FeaturesProtectedByListData = {
    body?: never;
    path: {
        protector_id: number;
    };
    query: {
        /**
         * RCP (Representative Concentration Pathway) value
         */
        rcp: string;
    };
    url: '/features/{protector_id}/protected-by';
};

export type FeaturesProtectedByListResponses = {
    200: Array<ProtectedFeature>;
};

export type FeaturesProtectedByListResponse = FeaturesProtectedByListResponses[keyof FeaturesProtectedByListResponses];

export type FeaturesSortedByRetrieveData = {
    body?: never;
    path: {
        field_group: string;
    };
    query: {
        /**
         * Filter by asset type
         */
        asset_type?: string;
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to sort by
         */
        field: string;
        /**
         * Filter by layer
         */
        layer?: string;
        /**
         * Page number (default 1)
         */
        page?: number;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
        /**
         * Filter by sector
         */
        sector?: string;
        /**
         * Page size (default 50)
         */
        size?: number;
        /**
         * Filter by subsector
         */
        subsector?: string;
    };
    url: '/features/sorted-by/{field_group}';
};

export type FeaturesSortedByRetrieveResponses = {
    200: PaginatedSortedFeatureListResponse;
};

export type FeaturesSortedByRetrieveResponse = FeaturesSortedByRetrieveResponses[keyof FeaturesSortedByRetrieveResponses];
