// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type AdaptationCostBenefit = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type AttributeLookupRequest = {
    ids: Array<number>;
};

/**
 * Serializer for colormap data
 */
export type ColorMap = {
    colormap: Array<ColorMapEntry>;
};

/**
 * Serializer for a single colormap entry (RGB)
 */
export type ColorMapEntry = {
    value: number;
    rgba: [
        number,
        number,
        number,
        number
    ];
};

export type CurrentUser = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type DamagesExpected = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpv = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRp = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type Feature = {
    readonly id: number;
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetail = {
    readonly id: number;
    readonly adaptation: Array<AdaptationCostBenefit>;
    readonly damages_expected: Array<DamagesExpected>;
    readonly damages_return_period: Array<DamagesRp>;
    readonly damages_npv: Array<DamagesNpv>;
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type InfrastructureNode = {
    node_id: string;
    node_name: string;
    parent?: string | null;
    readonly children: Array<InfrastructureNode>;
};

export type LoginCsrfErrorResponse = {
    detail: string;
};

export type LoginErrorResponse = {
    detail: string;
};

export type LoginRequest = {
    username: string;
};

export type LogoutCsrfErrorResponse = {
    detail: string;
};

export type MapConfig = {
    config_name: string;
    config_value: string;
};

export type PaginatedAdaptationCostBenefitList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefit>;
};

export type PaginatedDamagesExpectedList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpected>;
};

export type PaginatedDamagesRpList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRp>;
};

export type PaginatedFeatureList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Feature>;
};

export type PaginatedInfrastructureNodeList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InfrastructureNode>;
};

export type PaginatedMapConfigList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MapConfig>;
};

export type PaginatedSortedFeatureListResponse = {
    items: Array<SortedFeature>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

export type PatchedAdaptationCostBenefit = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    adaptation_name?: string;
    adaptation_protection_level?: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesExpected = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    epoch?: number;
    protection_standard?: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesRp = {
    readonly pk?: string;
    hazard?: string;
    rcp?: string;
    epoch?: number;
    rp?: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature?: number;
};

export type PatchedFeature = {
    readonly id?: number;
    string_id?: string;
    layer?: string;
    sublayer?: string | null;
    properties?: unknown;
};

/**
 * Serialize point_query payload: column names to value lists.
 */
export type PixelData = {
    key?: Array<string>;
    hazard?: Array<string>;
    rp?: Array<number | null>;
    rcp?: Array<string>;
    epoch?: Array<number | null>;
    confidence?: Array<number | null>;
    variable?: Array<string>;
    unit?: Array<string>;
    band_data?: Array<number | null>;
};

export type ProtectedFeature = {
    id: number;
    string_id: string;
    layer: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    adaptation_cost: number | null;
    avoided_ead_mean: number | null;
    avoided_eael_mean: number | null;
    hazard: string;
    rcp: string;
};

export type RasterTileSource = {
    readonly id: number;
    domain: string;
    name: string;
    group: string;
    description?: string | null;
    license?: string | null;
    keys: Array<string>;
};

export type RasterTileSourceDomains = {
    domains: Array<{
        [key: string]: string;
    }>;
};

export type SessionState = {
    authenticated: boolean;
    user: CurrentUser | null;
};

export type SortedFeature = {
    id: number;
    string_id: string;
    layer: string;
    bbox_wkt: string;
    value: number | null;
};

export type AdaptationCostBenefitWritable = {
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type CurrentUserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type DamagesExpectedWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpvWritable = {
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRpWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type FeatureWritable = {
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetailWritable = {
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type InfrastructureNodeWritable = {
    node_id: string;
    node_name: string;
    parent?: string | null;
};

export type LoginRequestWritable = {
    username: string;
    password: string;
};

export type PaginatedAdaptationCostBenefitListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefitWritable>;
};

export type PaginatedDamagesExpectedListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpectedWritable>;
};

export type PaginatedDamagesRpListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRpWritable>;
};

export type PaginatedFeatureListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<FeatureWritable>;
};

export type PaginatedInfrastructureNodeListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InfrastructureNodeWritable>;
};

export type PatchedAdaptationCostBenefitWritable = {
    hazard?: string;
    rcp?: string;
    adaptation_name?: string;
    adaptation_protection_level?: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesExpectedWritable = {
    hazard?: string;
    rcp?: string;
    epoch?: number;
    protection_standard?: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature?: number;
};

export type PatchedDamagesRpWritable = {
    hazard?: string;
    rcp?: string;
    epoch?: number;
    rp?: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature?: number;
};

export type PatchedFeatureWritable = {
    string_id?: string;
    layer?: string;
    sublayer?: string | null;
    properties?: unknown;
};

export type RasterTileSourceWritable = {
    domain: string;
    name: string;
    group: string;
    description?: string | null;
    license?: string | null;
    keys: Array<string>;
};

export type SessionStateWritable = {
    authenticated: boolean;
    user: CurrentUserWritable | null;
};

export type AdaptationCostBenefitsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/adaptation-cost-benefits';
};

export type AdaptationCostBenefitsListResponses = {
    200: PaginatedAdaptationCostBenefitList;
};

export type AdaptationCostBenefitsListResponse = AdaptationCostBenefitsListResponses[keyof AdaptationCostBenefitsListResponses];

export type AdaptationCostBenefitsCreateData = {
    body: AdaptationCostBenefitWritable;
    path?: never;
    query?: never;
    url: '/adaptation-cost-benefits';
};

export type AdaptationCostBenefitsCreateResponses = {
    201: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsCreateResponse = AdaptationCostBenefitsCreateResponses[keyof AdaptationCostBenefitsCreateResponses];

export type AdaptationCostBenefitsDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type AdaptationCostBenefitsDestroyResponse = AdaptationCostBenefitsDestroyResponses[keyof AdaptationCostBenefitsDestroyResponses];

export type AdaptationCostBenefitsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsRetrieveResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsRetrieveResponse = AdaptationCostBenefitsRetrieveResponses[keyof AdaptationCostBenefitsRetrieveResponses];

export type AdaptationCostBenefitsPartialUpdateData = {
    body?: PatchedAdaptationCostBenefitWritable;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsPartialUpdateResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsPartialUpdateResponse = AdaptationCostBenefitsPartialUpdateResponses[keyof AdaptationCostBenefitsPartialUpdateResponses];

export type AdaptationCostBenefitsUpdateData = {
    body: AdaptationCostBenefitWritable;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/adaptation-cost-benefits/{pk}';
};

export type AdaptationCostBenefitsUpdateResponses = {
    200: AdaptationCostBenefit;
};

export type AdaptationCostBenefitsUpdateResponse = AdaptationCostBenefitsUpdateResponses[keyof AdaptationCostBenefitsUpdateResponses];

export type AttributesCreateData = {
    body: AttributeLookupRequest;
    path: {
        field_group: string;
    };
    query: {
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to look up
         */
        field: string;
        /**
         * Asset layer ID
         */
        layer: string;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
    };
    url: '/attributes/{field_group}';
};

export type AttributesCreateResponses = {
    200: {
        [key: string]: number | null;
    };
};

export type AttributesCreateResponse = AttributesCreateResponses[keyof AttributesCreateResponses];

export type AuthLoginCreateData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginCreateErrors = {
    /**
     * Invalid credentials.
     */
    401: LoginErrorResponse;
    /**
     * CSRF validation failed.
     */
    403: LoginCsrfErrorResponse;
};

export type AuthLoginCreateError = AuthLoginCreateErrors[keyof AuthLoginCreateErrors];

export type AuthLoginCreateResponses = {
    200: SessionState;
};

export type AuthLoginCreateResponse = AuthLoginCreateResponses[keyof AuthLoginCreateResponses];

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutCreateErrors = {
    /**
     * CSRF validation failed.
     */
    403: LogoutCsrfErrorResponse;
};

export type AuthLogoutCreateError = AuthLogoutCreateErrors[keyof AuthLogoutCreateErrors];

export type AuthLogoutCreateResponses = {
    200: SessionState;
};

export type AuthLogoutCreateResponse = AuthLogoutCreateResponses[keyof AuthLogoutCreateResponses];

export type AuthMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeRetrieveResponses = {
    200: SessionState;
};

export type AuthMeRetrieveResponse = AuthMeRetrieveResponses[keyof AuthMeRetrieveResponses];

export type DamagesExpectedListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/damages-expected';
};

export type DamagesExpectedListResponses = {
    200: PaginatedDamagesExpectedList;
};

export type DamagesExpectedListResponse = DamagesExpectedListResponses[keyof DamagesExpectedListResponses];

export type DamagesExpectedCreateData = {
    body: DamagesExpectedWritable;
    path?: never;
    query?: never;
    url: '/damages-expected';
};

export type DamagesExpectedCreateResponses = {
    201: DamagesExpected;
};

export type DamagesExpectedCreateResponse = DamagesExpectedCreateResponses[keyof DamagesExpectedCreateResponses];

export type DamagesExpectedDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DamagesExpectedDestroyResponse = DamagesExpectedDestroyResponses[keyof DamagesExpectedDestroyResponses];

export type DamagesExpectedRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedRetrieveResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedRetrieveResponse = DamagesExpectedRetrieveResponses[keyof DamagesExpectedRetrieveResponses];

export type DamagesExpectedPartialUpdateData = {
    body?: PatchedDamagesExpectedWritable;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedPartialUpdateResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedPartialUpdateResponse = DamagesExpectedPartialUpdateResponses[keyof DamagesExpectedPartialUpdateResponses];

export type DamagesExpectedUpdateData = {
    body: DamagesExpectedWritable;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-expected/{pk}';
};

export type DamagesExpectedUpdateResponses = {
    200: DamagesExpected;
};

export type DamagesExpectedUpdateResponse = DamagesExpectedUpdateResponses[keyof DamagesExpectedUpdateResponses];

export type DamagesRpListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/damages-rp';
};

export type DamagesRpListResponses = {
    200: PaginatedDamagesRpList;
};

export type DamagesRpListResponse = DamagesRpListResponses[keyof DamagesRpListResponses];

export type DamagesRpCreateData = {
    body: DamagesRpWritable;
    path?: never;
    query?: never;
    url: '/damages-rp';
};

export type DamagesRpCreateResponses = {
    201: DamagesRp;
};

export type DamagesRpCreateResponse = DamagesRpCreateResponses[keyof DamagesRpCreateResponses];

export type DamagesRpDestroyData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type DamagesRpDestroyResponse = DamagesRpDestroyResponses[keyof DamagesRpDestroyResponses];

export type DamagesRpRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpRetrieveResponses = {
    200: DamagesRp;
};

export type DamagesRpRetrieveResponse = DamagesRpRetrieveResponses[keyof DamagesRpRetrieveResponses];

export type DamagesRpPartialUpdateData = {
    body?: PatchedDamagesRpWritable;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpPartialUpdateResponses = {
    200: DamagesRp;
};

export type DamagesRpPartialUpdateResponse = DamagesRpPartialUpdateResponses[keyof DamagesRpPartialUpdateResponses];

export type DamagesRpUpdateData = {
    body: DamagesRpWritable;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/damages-rp/{pk}';
};

export type DamagesRpUpdateResponses = {
    200: DamagesRp;
};

export type DamagesRpUpdateResponse = DamagesRpUpdateResponses[keyof DamagesRpUpdateResponses];

export type FeaturesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/features';
};

export type FeaturesListResponses = {
    200: PaginatedFeatureList;
};

export type FeaturesListResponse = FeaturesListResponses[keyof FeaturesListResponses];

export type FeaturesCreateData = {
    body: FeatureWritable;
    path?: never;
    query?: never;
    url: '/features';
};

export type FeaturesCreateResponses = {
    201: Feature;
};

export type FeaturesCreateResponse = FeaturesCreateResponses[keyof FeaturesCreateResponses];

export type FeaturesDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type FeaturesDestroyResponse = FeaturesDestroyResponses[keyof FeaturesDestroyResponses];

export type FeaturesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesRetrieveResponses = {
    200: FeatureDetail;
};

export type FeaturesRetrieveResponse = FeaturesRetrieveResponses[keyof FeaturesRetrieveResponses];

export type FeaturesPartialUpdateData = {
    body?: PatchedFeatureWritable;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesPartialUpdateResponses = {
    200: Feature;
};

export type FeaturesPartialUpdateResponse = FeaturesPartialUpdateResponses[keyof FeaturesPartialUpdateResponses];

export type FeaturesUpdateData = {
    body: FeatureWritable;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/features/{id}';
};

export type FeaturesUpdateResponses = {
    200: Feature;
};

export type FeaturesUpdateResponse = FeaturesUpdateResponses[keyof FeaturesUpdateResponses];

export type FeaturesProtectedByListData = {
    body?: never;
    path: {
        protector_id: number;
    };
    query: {
        /**
         * RCP (Representative Concentration Pathway) value
         */
        rcp: string;
    };
    url: '/features/{protector_id}/protected-by';
};

export type FeaturesProtectedByListResponses = {
    200: Array<ProtectedFeature>;
};

export type FeaturesProtectedByListResponse = FeaturesProtectedByListResponses[keyof FeaturesProtectedByListResponses];

export type FeaturesSortedByRetrieveData = {
    body?: never;
    path: {
        field_group: string;
    };
    query: {
        /**
         * Filter by asset type
         */
        asset_type?: string;
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to sort by
         */
        field: string;
        /**
         * Filter by layer
         */
        layer?: string;
        /**
         * Page number (default 1)
         */
        page?: number;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
        /**
         * Filter by sector
         */
        sector?: string;
        /**
         * Page size (default 50)
         */
        size?: number;
        /**
         * Filter by subsector
         */
        subsector?: string;
    };
    url: '/features/sorted-by/{field_group}';
};

export type FeaturesSortedByRetrieveResponses = {
    200: PaginatedSortedFeatureListResponse;
};

export type FeaturesSortedByRetrieveResponse = FeaturesSortedByRetrieveResponses[keyof FeaturesSortedByRetrieveResponses];

export type InfrastructureTreeListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/infrastructure-tree';
};

export type InfrastructureTreeListResponses = {
    200: PaginatedInfrastructureNodeList;
};

export type InfrastructureTreeListResponse = InfrastructureTreeListResponses[keyof InfrastructureTreeListResponses];

export type InfrastructureTreeRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/infrastructure-tree/{id}';
};

export type InfrastructureTreeRetrieveResponses = {
    200: InfrastructureNode;
};

export type InfrastructureTreeRetrieveResponse = InfrastructureTreeRetrieveResponses[keyof InfrastructureTreeRetrieveResponses];

export type MapConfigListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map-config';
};

export type MapConfigListResponses = {
    200: PaginatedMapConfigList;
};

export type MapConfigListResponse = MapConfigListResponses[keyof MapConfigListResponses];

export type MapConfigRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this map config.
         */
        config_name: string;
    };
    query?: never;
    url: '/map-config/{config_name}';
};

export type MapConfigRetrieveResponses = {
    200: MapConfig;
};

export type MapConfigRetrieveResponse = MapConfigRetrieveResponses[keyof MapConfigRetrieveResponses];

export type PixelRetrieveData = {
    body?: never;
    path: {
        /**
         * Latitude in EPSG:4326.
         */
        lat: number;
        /**
         * Longitude in EPSG:4326.
         */
        lon: number;
    };
    query?: never;
    url: '/pixel/{lon}/{lat}';
};

export type PixelRetrieveResponses = {
    200: PixelData;
};

export type PixelRetrieveResponse = PixelRetrieveResponses[keyof PixelRetrieveResponses];

export type TilesRasterPngRetrieveData = {
    body?: never;
    path: {
        domain: string;
        keys: string;
        tile_x: number;
        tile_y: number;
        tile_z: number;
    };
    query?: {
        /**
         * Colormap name to use for rendering the tile. Set to "explicit" for categorical data.
         */
        colormap?: string;
        /**
         * JSON categorical map used when colormap=explicit.
         */
        explicit_color_map?: string;
        /**
         * Optional stretch range as a JSON array, e.g. [0, 10].
         */
        stretch_range?: string;
    };
    url: '/tiles/raster/{domain}/{keys}/{tile_z}/{tile_x}/{tile_y}.png';
};

export type TilesRasterPngRetrieveErrors = {
    /**
     * Invalid tile parameters.
     */
    400: unknown;
    /**
     * Unexpected tile rendering error.
     */
    500: unknown;
};

export type TilesRasterPngRetrieveResponses = {
    /**
     * Rendered raster tile response.
     */
    200: unknown;
};

export type RasterColormapData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Colormap name (e.g. 'viridis', 'plasma', etc.)
         */
        colormap: string;
        /**
         * Optional stretch range as a JSON array of two numbers, e.g. [0, 100]. If not provided, the full data range will be used.
         */
        stretch_range?: string;
    };
    url: '/tiles/raster/colormap';
};

export type RasterColormapErrors = {
    /**
     * Invalid colormap options.
     */
    400: unknown;
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
};

export type RasterColormapResponses = {
    200: ColorMap;
};

export type RasterColormapResponse = RasterColormapResponses[keyof RasterColormapResponses];

export type RasterTileSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tiles/raster/sources';
};

export type RasterTileSourcesResponses = {
    200: Array<RasterTileSource>;
};

export type RasterTileSourcesResponse = RasterTileSourcesResponses[keyof RasterTileSourcesResponses];

export type RasterTileSourceData = {
    body?: never;
    path: {
        source_id: number;
    };
    query?: never;
    url: '/tiles/raster/sources/{source_id}';
};

export type RasterTileSourceResponses = {
    200: RasterTileSource;
};

export type RasterTileSourceResponse = RasterTileSourceResponses[keyof RasterTileSourceResponses];

export type RasterTileSourceDomainsData = {
    body?: never;
    path: {
        source_id: number;
    };
    query?: never;
    url: '/tiles/raster/sources/{source_id}/domains';
};

export type RasterTileSourceDomainsResponses = {
    200: RasterTileSourceDomains;
};

export type RasterTileSourceDomainsResponse = RasterTileSourceDomainsResponses[keyof RasterTileSourceDomainsResponses];

export type TilesVectorRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tiles/vector/';
};

export type TilesVectorRetrieveErrors = {
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
    /**
     * Invalid upstream redirect target.
     */
    502: unknown;
    /**
     * Vector tile upstream service unavailable.
     */
    503: unknown;
};

export type TilesVectorRetrieveResponses = {
    /**
     * Proxied vector tile response.
     */
    200: unknown;
};

export type TilesVectorRetrieve2Data = {
    body?: never;
    path: {
        tile_path: string;
    };
    query?: never;
    url: '/tiles/vector/{tile_path}';
};

export type TilesVectorRetrieve2Errors = {
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
    /**
     * Invalid upstream redirect target.
     */
    502: unknown;
    /**
     * Vector tile upstream service unavailable.
     */
    503: unknown;
};

export type TilesVectorRetrieve2Responses = {
    /**
     * Proxied vector tile response.
     */
    200: unknown;
};
