// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type AdaptationCostBenefit = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type AttributeLookupRequest = {
    ids: Array<number>;
};

/**
 * Serializer for colormap data
 */
export type ColorMap = {
    colormap: Array<ColorMapEntry>;
};

/**
 * Serializer for a single colormap entry (RGB)
 */
export type ColorMapEntry = {
    value: number;
    rgba: [
        number,
        number,
        number,
        number
    ];
};

/**
 * * `number` - Number
 * * `string` - String
 * * `boolean` - Boolean
 */
export type ConfigTypeEnum = 'number' | 'string' | 'boolean';

export type CurrentUser = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type DamagesExpected = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpv = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRp = {
    readonly pk: string;
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type Dataset = {
    id: string;
    label: string;
    group: string;
    unit: string;
    stacking_order: number;
    display_order: number;
};

export type Feature = {
    readonly id: number;
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetail = {
    readonly id: number;
    readonly adaptation: Array<AdaptationCostBenefit>;
    readonly damages_expected: Array<DamagesExpected>;
    readonly damages_return_period: Array<DamagesRp>;
    readonly damages_npv: Array<DamagesNpv>;
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type InfrastructureNode = {
    node_id: string;
    node_name: string;
    parent?: string | null;
    readonly children: Array<InfrastructureNode>;
};

export type LoginCsrfErrorResponse = {
    detail: string;
};

export type LoginErrorResponse = {
    detail: string;
};

export type LoginRequest = {
    username: string;
};

export type Logo = {
    /**
     * The named page slot in which this logo should appear.
     */
    slot: string;
    readonly src: string;
    href: string;
    alt: string;
    /**
     * Displayed logo height in pixels.
     */
    height?: number;
};

export type LogoutCsrfErrorResponse = {
    detail: string;
};

export type MapConfig = {
    config_name: string;
    config_value: string;
    config_type?: ConfigTypeEnum;
};

export type MarkdownBlock = {
    slot: string;
    markdown: string;
};

export type Page = {
    name: string;
    title: string;
    readonly background_image: string | null;
    /**
     * Optional credit for the background image.
     */
    background_credit?: string | null;
};

export type PaginatedAdaptationCostBenefitList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefit>;
};

export type PaginatedDamagesExpectedList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpected>;
};

export type PaginatedDamagesRpList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRp>;
};

export type PaginatedDatasetList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Dataset>;
};

export type PaginatedFeatureList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Feature>;
};

export type PaginatedInfrastructureNodeList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InfrastructureNode>;
};

export type PaginatedMapConfigList = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<MapConfig>;
};

export type PaginatedSortedFeatureListResponse = {
    items: Array<SortedFeature>;
    total: number;
    page: number;
    size: number;
    pages: number;
};

/**
 * Serialize point_query payload: column names to value lists.
 */
export type PixelData = {
    key?: Array<string>;
    hazard?: Array<string>;
    rp?: Array<number | null>;
    rcp?: Array<string>;
    epoch?: Array<number | null>;
    confidence?: Array<number | null>;
    variable?: Array<string>;
    unit?: Array<string>;
    band_data?: Array<number | null>;
};

export type ProtectedFeature = {
    id: number;
    string_id: string;
    layer: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    adaptation_cost: number | null;
    avoided_ead_mean: number | null;
    avoided_eael_mean: number | null;
    hazard: string;
    rcp: string;
};

export type RasterTileSource = {
    readonly id: number;
    domain: string;
    name: string;
    group: string;
    description?: string | null;
    license?: string | null;
    keys: Array<string>;
};

export type RasterTileSourceDomains = {
    domains: Array<{
        [key: string]: string;
    }>;
};

export type RegistrationCsrfErrorResponse = {
    detail: string;
};

export type RegistrationErrorResponse = {
    detail: string;
};

export type RegistrationFailureResponse = {
    detail: string;
};

export type RegistrationRequest = {
    username: string;
    email: string;
};

export type RegistrationSuccessResponse = {
    detail: string;
};

export type SessionState = {
    authenticated: boolean;
    user: CurrentUser | null;
};

export type SortedFeature = {
    id: number;
    string_id: string;
    layer: string;
    bbox_wkt: string;
    value: number | null;
};

export type AdaptationCostBenefitWritable = {
    hazard: string;
    rcp: string;
    adaptation_name: string;
    adaptation_protection_level: number;
    protector_feature_id?: number | null;
    adaptation_cost?: number | null;
    avoided_ead_amin?: number | null;
    avoided_ead_mean?: number | null;
    avoided_ead_amax?: number | null;
    avoided_eael_amin?: number | null;
    avoided_eael_mean?: number | null;
    avoided_eael_amax?: number | null;
    feature: number;
};

export type CurrentUserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    first_name?: string;
    last_name?: string;
};

export type DamagesExpectedWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    protection_standard: number;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesNpvWritable = {
    hazard: string;
    rcp: string;
    ead_amin?: number | null;
    ead_mean?: number | null;
    ead_amax?: number | null;
    eael_amin?: number | null;
    eael_mean?: number | null;
    eael_amax?: number | null;
    feature: number;
};

export type DamagesRpWritable = {
    hazard: string;
    rcp: string;
    epoch: number;
    rp: number;
    exposure?: number | null;
    damage_amin?: number | null;
    damage_mean?: number | null;
    damage_amax?: number | null;
    loss_amin?: number | null;
    loss_mean?: number | null;
    loss_amax?: number | null;
    feature: number;
};

export type FeatureWritable = {
    string_id: string;
    layer: string;
    sublayer?: string | null;
    properties: unknown;
};

export type FeatureDetailWritable = {
    string_id: string;
    sublayer?: string | null;
    properties: unknown;
    geom: string;
    layer: string;
};

export type InfrastructureNodeWritable = {
    node_id: string;
    node_name: string;
    parent?: string | null;
};

export type LoginRequestWritable = {
    username: string;
    password: string;
};

export type LogoWritable = {
    /**
     * The named page slot in which this logo should appear.
     */
    slot: string;
    href: string;
    alt: string;
    /**
     * Displayed logo height in pixels.
     */
    height?: number;
};

export type PageWritable = {
    name: string;
    title: string;
    /**
     * Optional credit for the background image.
     */
    background_credit?: string | null;
};

export type PaginatedAdaptationCostBenefitListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<AdaptationCostBenefitWritable>;
};

export type PaginatedDamagesExpectedListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesExpectedWritable>;
};

export type PaginatedDamagesRpListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<DamagesRpWritable>;
};

export type PaginatedFeatureListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<FeatureWritable>;
};

export type PaginatedInfrastructureNodeListWritable = {
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<InfrastructureNodeWritable>;
};

export type RasterTileSourceWritable = {
    domain: string;
    name: string;
    group: string;
    description?: string | null;
    license?: string | null;
    keys: Array<string>;
};

export type RegistrationRequestWritable = {
    username: string;
    email: string;
    password: string;
};

export type SessionStateWritable = {
    authenticated: boolean;
    user: CurrentUserWritable | null;
};

export type AuthLoginCreateData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthLoginCreateErrors = {
    /**
     * Invalid credentials or unverified email address.
     */
    401: LoginErrorResponse;
    /**
     * CSRF validation failed.
     */
    403: LoginCsrfErrorResponse;
};

export type AuthLoginCreateError = AuthLoginCreateErrors[keyof AuthLoginCreateErrors];

export type AuthLoginCreateResponses = {
    200: SessionState;
};

export type AuthLoginCreateResponse = AuthLoginCreateResponses[keyof AuthLoginCreateResponses];

export type AuthLogoutCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutCreateErrors = {
    /**
     * CSRF validation failed.
     */
    403: LogoutCsrfErrorResponse;
};

export type AuthLogoutCreateError = AuthLogoutCreateErrors[keyof AuthLogoutCreateErrors];

export type AuthLogoutCreateResponses = {
    200: SessionState;
};

export type AuthLogoutCreateResponse = AuthLogoutCreateResponses[keyof AuthLogoutCreateResponses];

export type AuthMeRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeRetrieveResponses = {
    200: SessionState;
};

export type AuthMeRetrieveResponse = AuthMeRetrieveResponses[keyof AuthMeRetrieveResponses];

export type AuthRegisterCreateData = {
    body: RegistrationRequestWritable;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterCreateErrors = {
    /**
     * Invalid registration details.
     */
    400: RegistrationErrorResponse;
    /**
     * CSRF validation failed.
     */
    403: RegistrationCsrfErrorResponse;
    /**
     * Registration failed.
     */
    500: RegistrationFailureResponse;
};

export type AuthRegisterCreateError = AuthRegisterCreateErrors[keyof AuthRegisterCreateErrors];

export type AuthRegisterCreateResponses = {
    200: RegistrationSuccessResponse;
};

export type AuthRegisterCreateResponse = AuthRegisterCreateResponses[keyof AuthRegisterCreateResponses];

export type ContentListData = {
    body?: never;
    path: {
        page: string;
    };
    query?: never;
    url: '/content/{page}';
};

export type ContentListResponses = {
    200: Array<MarkdownBlock>;
};

export type ContentListResponse = ContentListResponses[keyof ContentListResponses];

export type ContentLogosListData = {
    body?: never;
    path: {
        page: string;
    };
    query?: never;
    url: '/content/{page}/logos';
};

export type ContentLogosListResponses = {
    200: Array<Logo>;
};

export type ContentLogosListResponse = ContentLogosListResponses[keyof ContentLogosListResponses];

export type ContentMetadataRetrieveData = {
    body?: never;
    path: {
        page: string;
    };
    query?: never;
    url: '/content/{page}/metadata';
};

export type ContentMetadataRetrieveResponses = {
    200: Page;
};

export type ContentMetadataRetrieveResponse = ContentMetadataRetrieveResponses[keyof ContentMetadataRetrieveResponses];

export type MapAdaptationCostBenefitsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/adaptation-cost-benefits';
};

export type MapAdaptationCostBenefitsListResponses = {
    200: PaginatedAdaptationCostBenefitList;
};

export type MapAdaptationCostBenefitsListResponse = MapAdaptationCostBenefitsListResponses[keyof MapAdaptationCostBenefitsListResponses];

export type MapAdaptationCostBenefitsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this adaptation cost benefit.
         */
        pk: string;
    };
    query?: never;
    url: '/map/adaptation-cost-benefits/{pk}';
};

export type MapAdaptationCostBenefitsRetrieveResponses = {
    200: AdaptationCostBenefit;
};

export type MapAdaptationCostBenefitsRetrieveResponse = MapAdaptationCostBenefitsRetrieveResponses[keyof MapAdaptationCostBenefitsRetrieveResponses];

export type MapAttributesCreateData = {
    body: AttributeLookupRequest;
    path: {
        field_group: string;
    };
    query: {
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to look up
         */
        field: string;
        /**
         * Asset layer ID
         */
        layer: string;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
    };
    url: '/map/attributes/{field_group}';
};

export type MapAttributesCreateResponses = {
    200: {
        [key: string]: number | null;
    };
};

export type MapAttributesCreateResponse = MapAttributesCreateResponses[keyof MapAttributesCreateResponses];

export type MapConfigListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/config';
};

export type MapConfigListResponses = {
    200: PaginatedMapConfigList;
};

export type MapConfigListResponse = MapConfigListResponses[keyof MapConfigListResponses];

export type MapConfigRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this map config.
         */
        config_name: string;
    };
    query?: never;
    url: '/map/config/{config_name}';
};

export type MapConfigRetrieveResponses = {
    200: MapConfig;
};

export type MapConfigRetrieveResponse = MapConfigRetrieveResponses[keyof MapConfigRetrieveResponses];

export type MapDamagesExpectedListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/damages-expected';
};

export type MapDamagesExpectedListResponses = {
    200: PaginatedDamagesExpectedList;
};

export type MapDamagesExpectedListResponse = MapDamagesExpectedListResponses[keyof MapDamagesExpectedListResponses];

export type MapDamagesExpectedRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages expected.
         */
        pk: string;
    };
    query?: never;
    url: '/map/damages-expected/{pk}';
};

export type MapDamagesExpectedRetrieveResponses = {
    200: DamagesExpected;
};

export type MapDamagesExpectedRetrieveResponse = MapDamagesExpectedRetrieveResponses[keyof MapDamagesExpectedRetrieveResponses];

export type MapDamagesRpListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/damages-rp';
};

export type MapDamagesRpListResponses = {
    200: PaginatedDamagesRpList;
};

export type MapDamagesRpListResponse = MapDamagesRpListResponses[keyof MapDamagesRpListResponses];

export type MapDamagesRpRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this damages rp.
         */
        pk: string;
    };
    query?: never;
    url: '/map/damages-rp/{pk}';
};

export type MapDamagesRpRetrieveResponses = {
    200: DamagesRp;
};

export type MapDamagesRpRetrieveResponse = MapDamagesRpRetrieveResponses[keyof MapDamagesRpRetrieveResponses];

export type MapDatasetsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/datasets';
};

export type MapDatasetsListResponses = {
    200: PaginatedDatasetList;
};

export type MapDatasetsListResponse = MapDatasetsListResponses[keyof MapDatasetsListResponses];

export type MapDatasetsRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique value identifying this dataset.
         */
        id: string;
    };
    query?: never;
    url: '/map/datasets/{id}';
};

export type MapDatasetsRetrieveResponses = {
    200: Dataset;
};

export type MapDatasetsRetrieveResponse = MapDatasetsRetrieveResponses[keyof MapDatasetsRetrieveResponses];

export type MapFeaturesListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/features';
};

export type MapFeaturesListResponses = {
    200: PaginatedFeatureList;
};

export type MapFeaturesListResponse = MapFeaturesListResponses[keyof MapFeaturesListResponses];

export type MapFeaturesRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this feature.
         */
        id: number;
    };
    query?: never;
    url: '/map/features/{id}';
};

export type MapFeaturesRetrieveResponses = {
    200: FeatureDetail;
};

export type MapFeaturesRetrieveResponse = MapFeaturesRetrieveResponses[keyof MapFeaturesRetrieveResponses];

export type MapFeaturesProtectedByListData = {
    body?: never;
    path: {
        protector_id: number;
    };
    query: {
        /**
         * RCP (Representative Concentration Pathway) value
         */
        rcp: string;
    };
    url: '/map/features/{protector_id}/protected-by';
};

export type MapFeaturesProtectedByListResponses = {
    200: Array<ProtectedFeature>;
};

export type MapFeaturesProtectedByListResponse = MapFeaturesProtectedByListResponses[keyof MapFeaturesProtectedByListResponses];

export type MapFeaturesSortedByRetrieveData = {
    body?: never;
    path: {
        field_group: string;
    };
    query: {
        /**
         * Filter by asset type
         */
        asset_type?: string;
        /**
         * JSON object with dimension filters
         */
        dimensions: string;
        /**
         * Field name to sort by
         */
        field: string;
        /**
         * Filter by layer
         */
        layer?: string;
        /**
         * Page number (default 1)
         */
        page?: number;
        /**
         * JSON object with field parameters
         */
        parameters?: string;
        /**
         * Filter by sector
         */
        sector?: string;
        /**
         * Page size (default 50)
         */
        size?: number;
        /**
         * Filter by subsector
         */
        subsector?: string;
    };
    url: '/map/features/sorted-by/{field_group}';
};

export type MapFeaturesSortedByRetrieveResponses = {
    200: PaginatedSortedFeatureListResponse;
};

export type MapFeaturesSortedByRetrieveResponse = MapFeaturesSortedByRetrieveResponses[keyof MapFeaturesSortedByRetrieveResponses];

export type MapInfrastructureTreeListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/map/infrastructure-tree';
};

export type MapInfrastructureTreeListResponses = {
    200: PaginatedInfrastructureNodeList;
};

export type MapInfrastructureTreeListResponse = MapInfrastructureTreeListResponses[keyof MapInfrastructureTreeListResponses];

export type MapInfrastructureTreeRetrieveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/map/infrastructure-tree/{id}';
};

export type MapInfrastructureTreeRetrieveResponses = {
    200: InfrastructureNode;
};

export type MapInfrastructureTreeRetrieveResponse = MapInfrastructureTreeRetrieveResponses[keyof MapInfrastructureTreeRetrieveResponses];

export type PixelRetrieveData = {
    body?: never;
    path: {
        /**
         * Latitude in EPSG:4326.
         */
        lat: number;
        /**
         * Longitude in EPSG:4326.
         */
        lon: number;
    };
    query?: never;
    url: '/pixel/{lon}/{lat}';
};

export type PixelRetrieveResponses = {
    200: PixelData;
};

export type PixelRetrieveResponse = PixelRetrieveResponses[keyof PixelRetrieveResponses];

export type TilesRasterPngRetrieveData = {
    body?: never;
    path: {
        domain: string;
        keys: string;
        tile_x: number;
        tile_y: number;
        tile_z: number;
    };
    query?: {
        /**
         * Colormap name to use for rendering the tile. Set to "explicit" for categorical data.
         */
        colormap?: string;
        /**
         * JSON categorical map used when colormap=explicit.
         */
        explicit_color_map?: string;
        /**
         * Optional stretch range as a JSON array, e.g. [0, 10].
         */
        stretch_range?: string;
    };
    url: '/tiles/raster/{domain}/{keys}/{tile_z}/{tile_x}/{tile_y}.png';
};

export type TilesRasterPngRetrieveErrors = {
    /**
     * Invalid tile parameters.
     */
    400: unknown;
    /**
     * Unexpected tile rendering error.
     */
    500: unknown;
};

export type TilesRasterPngRetrieveResponses = {
    /**
     * Rendered raster tile response.
     */
    200: unknown;
};

export type RasterColormapData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Colormap name (e.g. 'viridis', 'plasma', etc.)
         */
        colormap: string;
        /**
         * Optional stretch range as a JSON array of two numbers, e.g. [0, 100]. If not provided, the full data range will be used.
         */
        stretch_range?: string;
    };
    url: '/tiles/raster/colormap';
};

export type RasterColormapErrors = {
    /**
     * Invalid colormap options.
     */
    400: unknown;
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
};

export type RasterColormapResponses = {
    200: ColorMap;
};

export type RasterColormapResponse = RasterColormapResponses[keyof RasterColormapResponses];

export type RasterTileSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tiles/raster/sources';
};

export type RasterTileSourcesResponses = {
    200: Array<RasterTileSource>;
};

export type RasterTileSourcesResponse = RasterTileSourcesResponses[keyof RasterTileSourcesResponses];

export type RasterTileSourceData = {
    body?: never;
    path: {
        source_id: number;
    };
    query?: never;
    url: '/tiles/raster/sources/{source_id}';
};

export type RasterTileSourceResponses = {
    200: RasterTileSource;
};

export type RasterTileSourceResponse = RasterTileSourceResponses[keyof RasterTileSourceResponses];

export type RasterTileSourceDomainsData = {
    body?: never;
    path: {
        source_id: number;
    };
    query?: never;
    url: '/tiles/raster/sources/{source_id}/domains';
};

export type RasterTileSourceDomainsResponses = {
    200: RasterTileSourceDomains;
};

export type RasterTileSourceDomainsResponse = RasterTileSourceDomainsResponses[keyof RasterTileSourceDomainsResponses];

export type TilesVectorRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tiles/vector/';
};

export type TilesVectorRetrieveErrors = {
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
    /**
     * Invalid upstream redirect target.
     */
    502: unknown;
    /**
     * Vector tile upstream service unavailable.
     */
    503: unknown;
};

export type TilesVectorRetrieveResponses = {
    /**
     * Proxied vector tile response.
     */
    200: unknown;
};

export type TilesVectorRetrieve2Data = {
    body?: never;
    path: {
        tile_path: string;
    };
    query?: never;
    url: '/tiles/vector/{tile_path}';
};

export type TilesVectorRetrieve2Errors = {
    /**
     * Authentication required.
     */
    401: unknown;
    /**
     * Permission denied.
     */
    403: unknown;
    /**
     * Invalid upstream redirect target.
     */
    502: unknown;
    /**
     * Vector tile upstream service unavailable.
     */
    503: unknown;
};

export type TilesVectorRetrieve2Responses = {
    /**
     * Proxied vector tile response.
     */
    200: unknown;
};
