# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
from django.db import migrations
from django.contrib.gis.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureLayers',
            fields=[
                ('layer_name', models.CharField(
                    primary_key=True,
                    serialize=False
                )),
                ('sector', models.CharField()),
                ('subsector', models.CharField()),
                ('asset_type', models.CharField()),
            ],
            options={
                'db_table': 'feature_layers',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('string_id', models.CharField()),
                ('sublayer', models.CharField(blank=True, null=True)),
                ('properties', models.JSONField()),
                ('geom', models.GeometryField(srid=4326)),
                ('layer', models.ForeignKey(
                    db_column='layer',
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='map.featurelayers'
                )),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='DamagesRp',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'feature_id', 'hazard', 'rcp', 'epoch', 'rp',
                    blank=True, editable=False, primary_key=True,
                    serialize=False
                )),
                ('hazard', models.CharField(max_length=8)),
                ('rcp', models.CharField(max_length=8)),
                ('epoch', models.IntegerField()),
                ('rp', models.IntegerField()),
                ('exposure', models.FloatField(blank=True, null=True)),
                ('damage_amin', models.FloatField(blank=True, null=True)),
                ('damage_mean', models.FloatField(blank=True, null=True)),
                ('damage_amax', models.FloatField(blank=True, null=True)),
                ('loss_amin', models.FloatField(blank=True, null=True)),
                ('loss_mean', models.FloatField(blank=True, null=True)),
                ('loss_amax', models.FloatField(blank=True, null=True)),
                ('feature', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='map.features'
                )),
            ],
            options={
                'db_table': 'damages_rp',
            },
        ),
        migrations.CreateModel(
            name='DamagesNpv',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'feature_id', 'hazard', 'rcp',
                    blank=True, editable=False, primary_key=True,
                    serialize=False
                )),
                ('hazard', models.CharField(max_length=8)),
                ('rcp', models.CharField(max_length=8)),
                ('ead_amin', models.FloatField(blank=True, null=True)),
                ('ead_mean', models.FloatField(blank=True, null=True)),
                ('ead_amax', models.FloatField(blank=True, null=True)),
                ('eael_amin', models.FloatField(blank=True, null=True)),
                ('eael_mean', models.FloatField(blank=True, null=True)),
                ('eael_amax', models.FloatField(blank=True, null=True)),
                ('feature', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='map.features'
                )),
            ],
            options={
                'db_table': 'damages_npv',
            },
        ),
        migrations.CreateModel(
            name='DamagesExpected',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'feature_id', 'hazard', 'rcp', 'epoch',
                    'protection_standard',
                    blank=True, editable=False, primary_key=True,
                    serialize=False
                )),
                ('hazard', models.CharField(max_length=8)),
                ('rcp', models.CharField(max_length=8)),
                ('epoch', models.IntegerField()),
                ('protection_standard', models.IntegerField()),
                ('ead_amin', models.FloatField(blank=True, null=True)),
                ('ead_mean', models.FloatField(blank=True, null=True)),
                ('ead_amax', models.FloatField(blank=True, null=True)),
                ('eael_amin', models.FloatField(blank=True, null=True)),
                ('eael_mean', models.FloatField(blank=True, null=True)),
                ('eael_amax', models.FloatField(blank=True, null=True)),
                ('feature', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='map.features'
                )),
            ],
            options={
                'db_table': 'damages_expected',
            },
        ),
        migrations.CreateModel(
            name='AdaptationCostBenefit',
            fields=[
                ('pk', models.CompositePrimaryKey(
                    'feature_id', 'hazard', 'rcp',
                    'adaptation_name', 'adaptation_protection_level',
                    blank=True, editable=False, primary_key=True,
                    serialize=False
                )),
                ('hazard', models.CharField(max_length=8)),
                ('rcp', models.CharField(max_length=8)),
                ('adaptation_name', models.CharField()),
                ('adaptation_protection_level', models.FloatField()),
                ('adaptation_cost', models.FloatField(blank=True, null=True)),
                ('avoided_ead_amin', models.FloatField(blank=True, null=True)),
                ('avoided_ead_mean', models.FloatField(blank=True, null=True)),
                ('avoided_ead_amax', models.FloatField(blank=True, null=True)),
                ('avoided_eael_amin', models.FloatField(
                    blank=True, null=True
                )),
                ('avoided_eael_mean', models.FloatField(
                    blank=True, null=True
                )),
                ('avoided_eael_amax', models.FloatField(
                    blank=True, null=True
                )),
                ('protector_feature_id', models.IntegerField(
                    blank=True, null=True
                )),
                ('feature', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='map.features'
                )),
            ],
            options={
                'db_table': 'adaptation_cost_benefit',
            },
        ),
    ]
