# Generated by Django 6.0.5 on 2026-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='FeatureLayers',
            new_name='FeatureLayer',
        ),
    ]
