# Generated by Django 6.0.5 on 2026-05-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_features_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationcostbenefit',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='map.feature'),
        ),
        migrations.AlterField(
            model_name='damagesexpected',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='map.feature'),
        ),
        migrations.AlterField(
            model_name='damagesnpv',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='map.feature'),
        ),
        migrations.AlterField(
            model_name='damagesrp',
            name='feature',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='map.feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(
                db_column='layer',
                on_delete=django.db.models.deletion.CASCADE,
                to='map.featurelayer',
            ),
        ),
    ]
