# Generated by Django 6.0.7 on 2026-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapconfig',
            name='config_type',
            field=models.CharField(
                choices=[
                    ('number', 'Number'),
                    ('string', 'String'),
                    ('boolean', 'Boolean')
                ],
                default='number'
            ),
        ),
    ]
