# Generated by Django 6.0.5 on 2026-06-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_adaptationcostbenefit_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('config_name', models.CharField(primary_key=True, serialize=False)),
                ('config_value', models.CharField()),
            ],
            options={
                'db_table': 'map_config',
            },
        ),
    ]
