# Generated by Django 6.0.5 on 2026-06-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mapconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureNode',
            fields=[
                (
                    'position',
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    'node_id',
                    models.CharField(primary_key=True, serialize=False),
                ),
                ('node_name', models.CharField()),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='api.infrastructurenode',
                        verbose_name='parent',
                    ),
                ),
            ],
            options={
                'db_table': 'infrastructure_nodes',
            },
        ),
    ]
