# Generated by Django 6.0.6 on 2026-07-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infrastructurenode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructurenode',
            options={'ordering': ['position']},
        ),
    ]
