# Generated by Django 6.0.5 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarkdownBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("page", models.CharField(max_length=20)),
                ("slot", models.CharField(max_length=20)),
                ("markdown", models.TextField()),
            ],
            options={
                "ordering": ["page", "slot"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "slot"),
                        name="unique_markdown_block_page_slot",
                    ),
                ],
                "db_table": "markdown_block",
            },
        ),
    ]
