# Generated by Django 6.0.7 on 2026-07-14 14:25

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_intro_markdown_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownblock',
            name='markdown',
            field=martor.models.MartorField(),
        ),
    ]
