# Generated by Django 6.0.5 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_markdownblock_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text=(
                            "The organisation name, also used as the image "
                            "alt text."
                        ),
                        max_length=200,
                    ),
                ),
                ("page", models.CharField(default="intro", max_length=20)),
                (
                    "slot",
                    models.CharField(
                        help_text=(
                            "The named page slot in which this logo should "
                            "appear."
                        ),
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="logos/")),
                ("link", models.URLField()),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Displayed logo height in pixels.",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text=(
                            "Logos in the same slot are displayed in "
                            "ascending order."
                        ),
                    ),
                ),
            ],
            options={
                "db_table": "logo",
                "ordering": ["page", "slot", "position", "name"],
            },
        ),
    ]
