# Generated by Django 6.0.5 on 2026-07-15

from pathlib import Path

from django.core.files import File
from django.core.files.storage import default_storage
from django.db import migrations, models
import django.db.models.deletion
import martor.models


INTRO_TITLE = (
    "Climate-related risk analytics for transport, energy & water "
    "infrastructure in Jamaica"
)
INTRO_BACKGROUND_FILENAME = (
    "irma-2017_data-from-nasa-modis_processed-by-antti-lipponen_1280.jpg"
)
INTRO_BACKGROUND_NAME = f"backgrounds/{INTRO_BACKGROUND_FILENAME}"


def add_pages(apps, schema_editor):
    Logo = apps.get_model("content", "Logo")
    MarkdownBlock = apps.get_model("content", "MarkdownBlock")
    Page = apps.get_model("content", "Page")

    page_names = set(
        MarkdownBlock.objects.values_list("page", flat=True).distinct()
    )
    page_names.update(Logo.objects.values_list("page", flat=True).distinct())
    page_names.add("intro")

    credit_block = MarkdownBlock.objects.filter(
        page="intro",
        slot="background-credit",
    ).first()

    if not default_storage.exists(INTRO_BACKGROUND_NAME):
        source_path = (
            Path(__file__).resolve().parents[1]
            / "defaults"
            / INTRO_BACKGROUND_FILENAME
        )
        with source_path.open("rb") as source:
            default_storage.save(INTRO_BACKGROUND_NAME, File(source))

    for name in page_names:
        Page.objects.create(
            name=name,
            title=(
                INTRO_TITLE
                if name == "intro"
                else name.replace("-", " ").title()
            ),
            background_image=(
                INTRO_BACKGROUND_NAME if name == "intro" else None
            ),
            background_credit=(
                credit_block.markdown
                if name == "intro" and credit_block
                else None
            ),
        )

    if credit_block:
        credit_block.delete()


def remove_pages(apps, schema_editor):
    MarkdownBlock = apps.get_model("content", "MarkdownBlock")
    Page = apps.get_model("content", "Page")

    intro_page = Page.objects.filter(name="intro").first()
    if intro_page and intro_page.background_credit:
        MarkdownBlock.objects.get_or_create(
            page="intro",
            slot="background-credit",
            defaults={
                "title": "Background image credit",
                "markdown": intro_page.background_credit,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional background image for the page.",
                        null=True,
                        upload_to="backgrounds/",
                    ),
                ),
                (
                    "background_credit",
                    martor.models.MartorField(
                        blank=True,
                        help_text=(
                            "Optional credit for the background image."
                        ),
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "page",
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(add_pages, remove_pages),
        migrations.AlterField(
            model_name="markdownblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content.page",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content.page",
            ),
        ),
    ]
