# Generated by Django 6.0.7 on 2026-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
