name: Create and publish canary Docker images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:frontend"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/nismod/irvapp-frontend:${{ github.ref_name }}
            ghcr.io/nismod/irvapp-frontend:canary
          secrets: |
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:irvapp"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/nismod/irvapp-backend:${{ github.ref_name }}
            ghcr.io/nismod/irvapp-backend:canary
          secrets: |
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
